config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get "/smart", to: "pages#smart"

  resources :users, only: :show
  get "/dashboard", to: "dashboard#dashboard"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :bounties, except: :destroy do
    resources :solutions, only: [:new, :create, :edit, :update]
    resources :homeworks, only: [:create, :destroy]

  end

  resources :solutions, only: [:show] do
    resources :messages, only: :create
  end
  patch 'solutions/:id', to: 'solutions#custom', as: 'validate_solution'
  # get 'bounty/:id', to: 'dashboard#homework', as: 'add_bounty'


  resources :solutions, only: [:destroy]
  #delete 'solutions/:id', to: 'solutions#destroy', as: 'destroy_solution'

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/bounty.rb
class Bounty < ApplicationRecord
  belongs_to :user
  has_many :homeworks, dependent: :destroy
  has_many :solutions, dependent: :destroy


  validates :content, :price_cents, :title, presence: true
  # validates :difficulty_level, inclusion: { in: (1..5),
  #   message: "%{value} is not a valid difficulty level you dumb fuck, it goes from 1 to 5" }

  def self.unsolved!
    Bounty.all.each do |bounty|
      if bounty.status == 'pending' && bounty.deadline && (bounty.deadline - (Date.today + 24)).negative?
        bounty.status = 'unsolved'
        bounty.save!
      end
    end
  end
end

app/controllers/bounties_controller.rb
class BountiesController < ApplicationController
  before_action :set_bounty, only: [:edit, :show, :update]
  def index
    @notifications = Notification.all
    @bounties = policy_scope(Bounty)
    @min_price = @bounties.sort_by(&:price_cents).first.price_cents
    @max_price = @bounties.sort_by(&:price_cents).last.price_cents
    if params[:query].present?
      sql_query = <<~SQL
        bounties.title  ILIKE :query
        OR users.username ILIKE :query
      SQL
      @bounties = @bounties.joins(:user).where(sql_query, query: "%#{params[:query]}%")
    end

    if params[:min].present? || params[:max].present?
      sql_query = <<~SQL
        price_cents  BETWEEN :min_value AND :max_value
      SQL
      @bounties = @bounties.where(sql_query, min_value: params[:min].to_f || @min_price, max_value: params[:max].to_f||@max_price)
    end
    if params[:difficulty_level].present?
      @bounties = @bounties.where(difficulty_level: params[:difficulty_level].to_i)
    end
  end

  def new
    @bounty = Bounty.new
    authorize @bounty
  end

  def create
    @bounty = Bounty.new(bounties_params)
    @bounty.user = current_user
    @bounty.price_cents = params[:price_cents]

    authorize @bounty
    if @bounty.save
      redirect_to bounty_path(@bounty)
    else
      render "new", status: :unprocessable_entity
    end
  end

  def show
    @message = Message.new
    @solution = Solution.new
    @solutions = @bounty.user == current_user ? Solution.where(bounty: @bounty) : current_user.solutions.where(bounty: @bounty)
    authorize @bounty
      if @bounty.github_repo.include?('github')
      if @bounty.github_repo.split("/")[4] == "rubyHunters"
        @github_path = "app/controllers/bounties_controller.rb"
      elsif (@repo_name != "rubyHunters")
        @github_path = @bounty.github_repo.split("/")[-3..].join("/")
        @github_name = @bounty.github_repo.split("/")[3]
        @repo_name = @bounty.github_repo.split("/")[4]
      end
    end
    @homework = Homework.new
  end

  def update
    @bounty.update(bounties_params)
    authorize @bounty
    redirect_to bounty_path(@bounty)
  end

  def edit
    authorize @bounty
  end

  private

  def bounties_params
    params.require(:bounty).permit(:title, :content, :price_cents, :github_repo, :deadline, :difficulty_level, :smartcontractaddress, :company)
  end

  def set_bounty
    @bounty = Bounty.find(params[:id])
  end
end

app/views/bounties/edit.html.erb
<h1>Edit this shit (bounty)</h1>
<div class="container">
  <div class="col-4 offset-4 my-5 pb-5">
    <h2 class="text-center">Edit a bounty </h2>
    <%= simple_form_for(@bounty) do |f| %>
      <%= f.input :title%>
      <%= f.input :content, :placeholder => "What is your coding problem" %>
      <%= f.input :difficulty_level %>
      <%= f.input :github_repo %>
      <%= f.submit class: 'btn btn-primary' %>
     <% end %>
  </div>
</div>

app/views/bounties/index.html.erb
<div class="index-container" data-controller="scroll-reveal">
  <div class="filter-container d-flex flex-column justify-content-center reveal" data-scroll-reveal-target="item">
    <p class="text-center mb-5">Price range</p>
    <%= form_with url: bounties_path,
                  method: :get,
                  html: {
                    data: {
                      controller: "range-input",
                      "range-input-min-value" => params[:min]|| @min_price ,
                      "range-input-max-value" => params[:max] || @max_price,
                      "range-input-max-price-value" => @max_price,
                      class: "pricing-filter"
                    }
                  } do %>
      <div class="price-box" data-range-input-target="range"></div>
      <%= text_field_tag :min, params[:min] || @min_price, 'data-range-input-target' => 'minInput', class: 'd-none' %>
      <%= text_field_tag :max, params[:max] || @max_price, 'data-range-input-target' => 'maxInput', class: 'd-none' %>
      <div class="tag-item difficulty-box">
        <p class="mb-3 text-center mt-3">Difficulty level</p>
        <div class="difficulty-level" style="border: #6F42C1 solid 1px;">
          <% (0..4).each do |i|%>
            <input type="checkbox" name="difficulty_level" id="difficulty_level_<%= i+1%>" value="<%= i+1%>" class="tag-selector" >
            <label for="difficulty_level_<%= i+1%>">level <%= i+1%></label>
          <% end %>
        </div>
      </div>
      <div class="btn-filter w-100">
        <%= submit_tag 'Apply', class: "btn chat-btn mb-2 mt-3 w-100" %>

        <%= text_field_tag :query,
          params[:query],
          class: "d-none"
        %>
      </div>
    <% end %>
  </div>
  <div class="bounty-container mb-3">
    <h2 class="title my-5 text-center">All <span class="green">open</span> bounties</h2>
    <div class="input-group rounded" style="margin-top: 4.7rem;">
      <%= form_with url: bounties_path, method: :get, html: {class: "d-flex"} do %>
        <%= text_field_tag :query,
            params[:query],
            class: "h-100",
            placeholder: "🔎  error 404 ..."
            %>
        <%#= submit_tag "".html_safe %>
        <%= button_tag 'search', class: "search-btn btn text-white me-1 ms-2 " %>


        <%= number_field_tag :min, params[:min] || 0, class: 'd-none' %>
        <%= number_field_tag :max, params[:max] || 50000, class: 'd-none' %>
      <% end %>
      <%# <%= link_to "Create a new bounty", new_bounty_path ,class: 'button-create' %>
    </div>
    <div class="bounties-card">
      <% @bounties.each_with_index do |bounty, i| %>
        <div class="bounty-card reveal" data-scroll-reveal-target="item" data-delay="<%= i*20 %>ms" >
          <%= link_to bounty_path(bounty), class:"flex-grow-1 text-decoration-none" do %>
            <div class="bounty-info">
              <div class="bounty-title">
                <p class="title-title">Title </p>
                <p class="content-title"><%= bounty.title %></p>
              </div>
              <div class="bounty-deadline">
                <p class="title">Deadline </p>
                <p class="content">
                  <% if bounty.deadline == nil %>
                    <%= "none" %>
                  <% else %>
                    <%= bounty.deadline %>
                  <% end %>
                </p>
              </div>
              <div class="bounty-price">
                <p class="title">Price </p>
                <p class="content"><%= bounty.price_cents %> eth.</p>
              </div>
              <div class="bounty-difficulty">
                <p class="title">Difficulty level </p>

                <% if bounty.difficulty_level %>
                  <%= image_tag "#{bounty.difficulty_level}-star.png" %>
                <% else %>
                  <p class=''>not specified</p>
                <% end %>

                <%# <p class="content"><%= bounty.difficulty_level</p> %>
              </div>
            </div>
          <% end %>
          <div class="bounty-links">
            <% if bounty.user.photo.attached? %>
              <%= cl_image_tag bounty.user.photo.key, class:"avatar-bounty" %>
            <% else %>
              <%= image_tag("blank-profile.png", class:"avatar-bounty") %>
            <% end %>
            <p class="title"><%= bounty.user.username %></p>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/bounties/new.html.erb
<div id="create-bounty">
  <div class ="pimp" data-controller="withdraw">
    <h5 class="text-center">Create a <span class="green">bounty</span></h5>
      <%= simple_form_for @bounty do |f| %>
        <div class="create-bounty-all">
          <div class="create-bounty-left">
            <span class="formfont" ><%= f.input :title, label: false, placeholder: 'Title'%></span>
            <span class="formfont" ><%= f.input :company, label: false, placeholder: 'Company name'%></span>
            <span class="formfont"><%= f.input :content, label: false, :placeholder => "Detail your coding problem" %></span>
            <span class="formfont"><%= f.input :difficulty_level, label: false, placeholder: 'Difficulty from 1 to 5' %></span>
          </div>
          <div class="create-bounty-right">
            <span class="formfont"><%= f.input :deadline, as: :string, input_html: { data: { controller: 'flatpickr' } }, label: false, placeholder: 'Optional: chose a deadline' %></span>
            <span class="formfont"><%= f.input :github_repo, label: false, :placeholder => "Link to your code"%></span>
            <div class="d-flex align-items-center justify-content-between">
              <p id="contractAccount">Contract Account: Not Connected</p>
              <%= f.input :smartcontractaddress, label: false, input_html: { data: { withdraw_target:'smartid'}, class:"d-none"} %>
              <button type="button" class="green-create" data-withdraw-target="connectContract" data-action="click->withdraw#connectContract click->withdraw#getContractAccount">Connect to contract</button>
            </div>
            <div id="writeArea" class="d-flex align-items-center justify-content-between d-none" data-withdraw-target="depositButton">
                <div class=" input-group">
                  <%= number_field_tag :price_cents, '1', class:"form-control", id:"depositInput", :placeholder => "Price" %>
                  <div class="input-group-append">
                    <span class="input-group-text">ETH</span>
                  </div>
                </div>
              <button type="button" class="green-create" data-action="click->withdraw#depositContract">Send money to contract</button>
            </div>
            <%= f.submit class: 'button2'%>
          </div>
          <%# <span class="formfont"><%= f.input :deadline, :input_html => {:value => Time.now}, start_year: Time.now.year, start_month: Time.now.month, start_day: Time.now.day</span> %>
        </div>
      <% end %>
  </div>
</div>